apiVersion: v2
description: ff-common chart building components and helpers for the Frank!Framework
name: ff-common
version: 0.1.17
appVersion: "7.8"
home: https://frankframework.org
icon: https://raw.githubusercontent.com/frankframework/charts/master/charts/ff-common/icon.svg

keywords:
  - library
