apiVersion: v2
appVersion: "latest"
description: A Helm chart for running Frank2Example on Kubernetes
name: frank2example
icon: https://raw.githubusercontent.com/ibissource/charts/master/charts/frank2example/icon.svg
type: application
version: 0.2.6

dependencies:
  - name: ff-common
    version: ~0.1.13
    repository: file://../ff-common
