apiVersion: v2
name: frank2example
description: A Helm chart for running Frank2Example on Kubernetes
version: 0.3.1
type: application
home: https://frankframework.org
icon: https://raw.githubusercontent.com/frankframework/charts/master/charts/frank2example/icon.svg

keywords:
  - demo

dependencies:
  - name: frankframework
    version: 0.3.2
    repository: file://../frankframework