{{/*
ConfigMap for generating a tomcat-users.xml including all users and roles
*/}}
{{- with .Values.application.security.http.localUsers -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frankframework.fullname" $ }}-local-users
  labels:
    {{- include "frankframework.labels" $ | nindent 4 }}
data:
  localUsers.yml: |-
    users:
      {{- toYaml . | nindent 6 -}}
{{- end -}}
