{{- if .Values.ladybugDatabase.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "frankframework.fullname" . }}-ladybug-database
  labels:
    {{- include "frankframework.ladybugLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    {{- include "frankframework.ladybugSelectorLabels" . | nindent 8 }}
{{- end -}}