apiVersion: v2
appVersion: "latest-tomcat"
description: A Helm chart for testing the Frank!Framework on Kubernetes
name: ff-test
icon: https://raw.githubusercontent.com/ibissource/charts/ff-common/charts/ff-test/icon.svg
type: application
version: 0.2.2

dependencies:
  - name: ff-common
    version: 0.1.1
    repository: file://../ff-common
